config/routes.rb
Gscms::Application.routes.draw do

  devise_for :admins, path: "admin", path_names: {sign_in: "login", sign_out: "logout"}


  namespace :admin do
    resources :admins,  except: [:show]
    resources :uploads, except: [:show, :edit, :update]
    resources :menus,   except: [:show] do
       post :page_sort, on: :collection
    end

    get "settings/homepage",       to: "settings#homepage",      as: :settings
    post "settings/homepage-save", to:  "settings#homepage_save", as: :homepage_save

    resources :pages do
       get   "sitemap",       on: :collection, as: :sitemap
       get   "clear_cache",   on: :collection, as: :clear_cache
    end
  end

  get ":permalink", to: "pages#show", as: :permalink
  root to: "pages#index"

   # Note: This route will make all actions in every controller accessible via GET requests.
   # match ':controller(/:action(/:id(.:format)))'
end

app/views/admin/pages/_ajax_error_show.html.erb
<% @page.errors.full_messages.each do |e| %><li><%= e %></li><% end %>

app/views/admin/pages/_form.html.erb
<%= form_for([:admin, @page], html: { class: "form_validations" }) do |f| %>
	<div class="module_content">
	<% if @page.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>
		  <ul>
		  <% @page.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>

		<%= f.label :name, raw("Name - <em>required</em>") %>
		<%= f.text_field :name, class: "validate[required] span12" %>

		<%= f.label :title, "Title <span id='title-count' class='char_count'></span>".html_safe %>
		<%= f.text_field :title, class: "span12" %>

		<%= f.label :meta_description, "Meta Description - <span id='meta-desc-count' class='char_count'></span>".html_safe %>
		<%= f.text_area :meta_description, class: "span12" %>

		<%= f.label :content, "Content - <span id='content-count' class='char_count'></span>".html_safe %>
		<%= f.text_area :content, class: "span12" %>

		<%= f.label :permalink, "Clean Url - <em>required</em>".html_safe %>
		<%= f.text_field :permalink, class: "validate[required] span12" %>

		<label class="checkbox">
			<% if action_name == "new" %>
				<%= f.check_box :active, checked: true %>
			<% else %>
				<%= f.check_box :active %>
			<% end %>
			Active
		</label>
	</div>
  <footer>
    	<%= f.submit "#{create_or_update_string} Page", class: "btn pull-right" %>
   </footer>
<% end %>

app/views/admin/pages/ajax_edit.html.erb
<%= javascript_include_tag "admin/form_validations"  %>
	<%= form_for([:admin, @page], :remote => true, :html => { :class => "update_ajax_page form_validations" }) do |f| %>
	  <% if @page.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>
	      <ul>
	      <% @page.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  	<%= f.label :name, "Name - <em>required</em>".html_safe %>
	  	<%= f.text_field :name, :class =>"validate[required]" %>
	  	<%= f.label :title, "Title <span id='title-count' class='char_count'></span>".html_safe %>
	  	<%= f.text_field :title %>
	  	<%= f.label :meta_description, "Meta Description <span id='meta-desc-count' class='char_count'></span>".html_safe %>
	  	<%= f.text_area :meta_description, :style => "height: 100px" %>
	  	<%= f.label :content, "Content <span id='content-count' class='char_count'></span>".html_safe %>
	  	<%= f.text_area :content %>
	  	<%= f.label :permalink, "Clean Url - <em>required</em>".html_safe %>
	  	<%= f.text_field :permalink, :class =>"validate[required]" %>	  	
  	
	  	<div class="checkbox_pair">
	  		<div class="checkbox_label"><%= f.label :active %></div>
	  		<div class="checkbox"><%= f.check_box :active, :checked => true %></div>
		</div>
		
	<div style="clear: both"></div>
	<% end %>

	<script>
		$(function() {
			checkTitleLength();
			checkMetadescLength();
			checkContentLength();
			
			$('#page_title').live('keyup click blur focus change paste', function() {
				checkTitleLength();
			});
			
			$('#page_meta_description').live('keyup click blur focus change paste', function() {
				checkMetadescLength();
			});
	
			$('#page_content').live('keyup click blur focus change paste', function() {
				checkContentLength();
			});
		});
	</script>

app/views/admin/pages/edit.html.erb
<article class="module">
	<header><h3>Edit Page</h3></header>
	<%= render 'form' %>
</article>

app/views/admin/pages/failed_content_update.js.erb
<% tmp_error_list = "" %>
<% @page.errors.full_messages.each do |msg| %>
<% tmp_error_list += "<li>#{msg}</li>" %>
<% end %>
$("#flash_message").prepend('<div class="alert alert-error"><h4>Error!</h4>Problem updating page.<ul><%= escape_javascript(tmp_error_list.html_safe) %></ul><button type="button" class="close" data-dismiss="alert">&times;</button></div>');

app/views/admin/pages/failed_update.js.erb
$("#flash_message").prepend('<h4 class="alert_error">Problem updating page. <span class="flash-close-icon-fail close-me"></span><ul><%= escape_javascript(render "ajax_error_show") %></ul></h4>');

app/views/admin/pages/index.html.erb
<article class="module">
	<header><h3>All Pages</h3></header>
		<table id="datatable_5_3" class="table table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Clean Url</th>
					<th>Active</th>
					<th>Created</th>
					<th>Updated</th>
					<th class="index_action">Edit Content</th>
					<th class="index_action">Edit Page</th>
					<th class="index_action">Delete</th>
				</tr>
			</thead>
			<tbody>
				<% @pages.each do |page| %>
				<tr class="<%= cycle("odd", "even") %>" id="<%= dom_id(page) %>">
					<td id="<%= dom_id(page, "name") %>"><%= link_to page.name, check_permalink(page) %></td>
					<td id="<%= dom_id(page, "permalink") %>"><%= page.permalink %></td>
					<td id="<%= dom_id(page, "active") %>"><%= page.active %></td>
					<td id="<%= dom_id(page, "created_at") %>"><%= page.created_at %></td>
					<td id="<%= dom_id(page, "updated_at") %>"><%= page.updated_at %></td>
					<td><%= link_to "Edit Content", admin_page_path(page), class: "btn btn-primary" %></td>
					<td><%= link_to 'Edit', edit_admin_page_path(page), class: "btn btn-primary" %></td>
					<td><%= link_to 'Destroy', [:admin, page], confirm: 'Are you sure?', method: :delete, class: "btn btn-danger" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
</article><!-- end of stats article -->

app/views/admin/pages/new.html.erb
<article class="module">
	<header><h3>New Page</h3></header>
	<%= render 'form' %>
</article>

app/views/admin/pages/quick_edit.html.erb
<%= javascript_include_tag "admin/form_validations"  %>
	<%= form_for([:admin, @page], :remote => true, :url => { :action => "quick_update" }, :html => { :class => "update_ajax_page form_validations" }) do |f| %>
	  <% if @page.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>
	      <ul>
	      <% @page.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  	<%= f.label :name, "Name - <em>required</em>".html_safe %>
	  	<%= f.text_field :name, :class =>"validate[required]" %>
	  	<%= f.label :title, "Title <span id='title-count' class='char_count'></span>".html_safe %>
	  	<%= f.text_field :title %>
	  	<%= f.label :meta_description, "Meta Description <span id='meta-desc-count' class='char_count'></span>".html_safe %>
	  	<%= f.text_area :meta_description, :style => "height: 100px" %>
	  	<%= f.label :content, "Content <span id='content-count' class='char_count'></span>".html_safe %>
	  	<%= f.text_area :content %>
	  	<%= f.label :permalink, "Clean Url - <em>required</em>".html_safe %>
	  	<%= f.text_field :permalink, :class =>"validate[required]" %>	  	
  	
	  	<div class="checkbox_pair">
	  		<div class="checkbox_label"><%= f.label :active %></div>
	  		<div class="checkbox"><%= f.check_box :active, :checked => true %></div>
		</div>
		
	<div style="clear: both"></div>
	<% end %>

	<script>
		$(function() {
			checkTitleLength();
			checkMetadescLength();
			checkContentLength();
			
			$('#page_title').live('keyup click blur focus change paste', function() {
				checkTitleLength();
			});
			
			$('#page_meta_description').live('keyup click blur focus change paste', function() {
				checkMetadescLength();
			});
	
			$('#page_content').live('keyup click blur focus change paste', function() {
				checkContentLength();
			});
		});
	</script>

app/views/admin/pages/show.html.erb
<%= form_for([:admin, @page], remote: true, html: { class: "update_ajax_page form_validations" }) do |f| %>
  <div class="content_preview">
    <%= raw @page.content %>
  </div>

  <div id="draggable_editor">
    <div id="handle">
      <span class="icon-move"></span>
        <%= link_to "Back to Admin Panel", admin_pages_path, confirm: 'Are you sure?' %>
      <span class="icon-move"></span>
    </div>

    <div id="flash_message"></div>
    <%= f.text_area :content, id: 'multiSet' %>
    <%= f.submit "Update Content", class: "btn update_content" %>
    <div style="clear: both"></div>
  </div>
<% end %>

<% content_for :custom_styling do %>
  <%= stylesheet_link_tag "admin/admin_page_show" %>
  <%= javascript_include_tag "admin/admin_page_show" %>
<% end %>



<!-- File Manager Modal -->
<div id="file_manager_modal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3>File Manager</h3>
  </div>
  <div class="modal-body">
    <div id="file_manager_flash_message"></div>
    <ul class="nav nav-tabs" id="file-manager-ul">
      <li class="active"><a href="#file-upload-tab">File Upload</a></li>
      <li><a href="#file-insert-tab">Insert Uploaded Files</a></li>
    </ul>
    <div class="tab-content">

      <div class="tab-pane active" id="file-upload-tab"> <!-- File Upload Tab -->
        <div id="uploads_table" class="file_table"></div>
        <%= form_for([:admin, Upload.new], remote: true, html: { style: "margin-bottom: 10px" }) do |f| %>
          <div class="fileinput-button-box" style="text-align: center; margin-left: 190px;">
            <span class="btn btn-success fileinput-button">
            <i class="icon-plus icon-white"></i>
            <span>Add Upload...</span>
              <%= f.file_field :upload, multiple: true, name: "upload[upload]" %>
            </span>
          </div>
        <% end %>
        <div style="text-align: center">OR</div>
        <div id="dropzone" class="fade well" style="text-align: center;">...drag 'n' drop your file in this area.</div>
      </div> <!-- End of File Upload Tab -->

      <div class="tab-pane" id="file-insert-tab"> <!-- File Insert Tab -->
        <table class="upload-table">
          <% @uploads.each do |upload| %>
            <%= render partial: "admin/uploads/upload_row", locals: { upload: upload } %>
          <% end %>
        </table>
      </div> <!-- File Insert Tab -->
    </div>
        <div>
        </div>

  </div>

  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>

<script id="template-upload" type="text/x-tmpl">
  <div class="upload">
    {%=o.name%}
    <div class="progress"><div class="bar" style="width: 0%"></div></div>
  </div>
</script>

</div><!-- End File Manager Modal -->

app/views/admin/pages/success_content_update.js.erb
$("#flash_message").prepend('<div class="alert alert-success"><h4>Success!</h4>Page <span class="page_name"><%= @page.name %></span> was successfully updated.<button type="button" class="close" data-dismiss="alert">&times;</button></div>');

app/views/admin/pages/success_update.js.erb
$(".popup #main").prepend('<h4 class="alert_success">Page <span class="page_name"><%= @page.name %></span> was successfully updated. <span class="flash-close-icon-success close-me"></span></h4>');


$("#name_page_<%= @page.id %>").text("<%= @page.name %>");
$("#permalink_page_<%= @page.id %>").text("<%= @page.permalink %>");
$("#active_page_<%= @page.id %>").text("<%= @page.active %>");
$("#updated_at_page_<%= @page.id %>").text("<%= @page.updated_at %>");