config/routes.rb
Gscms::Application.routes.draw do

  devise_for :admins, path: "admin", path_names: {sign_in: "login", sign_out: "logout"}


  namespace :admin do
    resources :admins,  except: [:show]
    resources :uploads, except: [:show, :edit, :update]
    resources :menus,   except: [:show] do
       post :page_sort, on: :collection
    end

    get "settings/homepage",       to: "settings#homepage",      as: :settings
    post "settings/homepage-save", to:  "settings#homepage_save", as: :homepage_save

    resources :pages do
       get   "sitemap",       on: :collection, as: :sitemap
       get   "clear_cache",   on: :collection, as: :clear_cache
    end
  end

  get ":permalink", to: "pages#show", as: :permalink
  root to: "pages#index"

   # Note: This route will make all actions in every controller accessible via GET requests.
   # match ':controller(/:action(/:id(.:format)))'
end

app/views/admin/admins/_form.html.erb
<%= form_for([:admin, @admin], html: { class: "form_validations" }) do |f| %>
<div class="module_content">
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>
      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "validate[required, custom[email]] span12" %>
    <% if controller.action_name == "new" %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "validate[required] span12" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "validate[required] span12" %>
  <% else %>
    <%= f.label :password, raw("Password - <i>(leave it blank if you don't want to change it)</i>") %>
    <%= f.password_field :password, class: "span12" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "span12" %>
  <% end %>

</div>
  <footer>
    <%= f.submit "#{create_or_update_string} Admin", class: "btn pull-right" %>
  </footer>
<% end %>

app/views/admin/admins/edit.html.erb
<article class="module">
	<header><h3>Edit Admin</h3></header>
	<%= render 'form' %>
</article>

app/views/admin/admins/index.html.erb
<article class="module">
	<header><h3>All Admins</h3></header>
		<table id="datatable_3_2" class="table table-hover">
			<thead>
				<tr>
					<th>Email</th>
					<th>Created</th>
					<th>Updated</th>
					<th class="index_action">Edit</th>
					<th class="index_action">Delete</th>
				</tr>
			</thead>
			<tbody>
				<% @admins.each do |admin| %>
				<tr>
					<td><%= admin.email %></td>
					<td><%= admin.created_at %></td>
					<td><%= admin.updated_at %></td>
					<td><%= link_to 'Edit', edit_admin_admin_path(admin), class: "btn btn-primary" %></td>
					<td><%= link_to 'Destroy', [:admin, admin], confirm: 'Are you sure?', method: :delete, class: "btn btn-danger" %></td>
				</tr>
				<% end %>
				</tbody>
		</table>
</article><!-- end of stats article -->

app/views/admin/admins/new.html.erb
<article class="module">
	<header><h3>New Admin</h3></header>
	<%= render 'form' %>
</article>