config/routes.rb
Gscms::Application.routes.draw do

  devise_for :admins, path: "admin", path_names: {sign_in: "login", sign_out: "logout"}


  namespace :admin do
    resources :admins,  except: [:show]
    resources :uploads, except: [:show, :edit, :update]
    resources :menus,   except: [:show] do
       post :page_sort, on: :collection
    end

    get "settings/homepage",       to: "settings#homepage",      as: :settings
    post "settings/homepage-save", to:  "settings#homepage_save", as: :homepage_save

    resources :pages do
       get   "sitemap",       on: :collection, as: :sitemap
       get   "clear_cache",   on: :collection, as: :clear_cache
    end
  end

  get ":permalink", to: "pages#show", as: :permalink
  root to: "pages#index"

   # Note: This route will make all actions in every controller accessible via GET requests.
   # match ':controller(/:action(/:id(.:format)))'
end

app/views/admin/partials/_breadcrumb.html.erb
<div class="breadcrumb_container">
  <article class="breadcrumb">
  	<% if controller.action_name == "index" %>
  		<a class="current"><%= controller.controller_name.titleize %></a>
  		<div class="breadcrumb_divider"></div>
  	  	<a class="current">All</a>
  	<% else %>
  	  	<%= link_to "#{controller.controller_name.titleize}", eval("admin_#{controller.controller_name}_path"), class: "current" %>
  	  	<div class="breadcrumb_divider"></div>
  	  	<a class="current"><%= controller.action_name.titleize %> <%= controller.controller_name.titleize.singularize %></a>
  	<% end %>
  </article>
</div>

app/views/admin/partials/_sidebar.html.erb
	<aside id="sidebar" class="fill">
		<section id="gradientTop">
			<h3 class="<%= "current_menu" if controller.controller_name == "pages" %>"><%= link_to "Pages", admin_pages_path %></h3>
			<ul class="toggle">
				<li class="<%= "current_action" if controller.controller_name == "pages" && controller.action_name == "index"  %>"><%= link_to "All Pages", admin_pages_path %></li>
				<li class="<%= "current_action" if controller.controller_name == "pages" && controller.action_name == "new"  %>"><%= link_to "New Page", new_admin_page_path %></li>
				<li class="<%= "current_action" if controller.controller_name == "pages" && controller.action_name == "sitemap"  %>"><%= link_to "Create Sitemap", sitemap_admin_pages_path  %></li>
			</ul>
			<br />
			<h3 class="<%= "current_menu" if controller.controller_name == "menus" %>"><%= link_to "Menus", admin_menus_path %></h3>
			<ul class="toggle">
				<li class="<%= "current_action" if controller.controller_name == "menus" && controller.action_name == "index" %>"><%= link_to "All Menus", admin_menus_path %></li>
				<li class="<%= "current_action" if controller.controller_name == "menus" && controller.action_name == "new" %>"><%= link_to "New Menu", new_admin_menu_path %></li>
			</ul>

			<br />
			<h3 class="<%= "current_menu" if controller.controller_name == "admin" %>"><%= link_to "Admins", admin_admins_path %></h3>
			<ul class="toggle">
				<li class="<%= "current_action" if controller.controller_name == "admin" && controller.action_name == "index"  %>"><%= link_to "All Admin", admin_admins_path %></li>
				<li class="<%= "current_action" if controller.controller_name == "admin" && controller.action_name == "new"  %>"><%= link_to "New Admin", new_admin_admin_path %></li>
			</ul>
      <br />
      <h3 class="<%= "current_menu" if controller.controller_name == "uploads" %>"><%= link_to "Uploads", admin_uploads_path %></h3>
      <ul class="toggle">
      	<li class="<%= "current_action" if controller.controller_name == "uploads" && controller.action_name == "index" %>"><%= link_to "All Uploads", admin_uploads_path %></li>
      	<li class="<%= "current_action" if controller.controller_name == "uploads" && controller.action_name == "new" %>"><%= link_to "New Upload", new_admin_upload_path %></li>
      </ul>

<!-- Before this, the generator will add it -->
			<br />
			<h3 class="<%= "current_menu" if controller.controller_name == "settings" %>"><%= link_to "Settings", admin_settings_path %></h3>
		</section>
		<footer>
			<hr />
			<p id="copyleft">
				<strong>Copyleft 2011 GreekSolution</strong>
				<br />
				<em>do whatever you want with this app! :D</em>
			</p>
		</footer>
	</aside><!-- end of sidebar -->