config/routes.rb
Gscms::Application.routes.draw do

  devise_for :admins, path: "admin", path_names: {sign_in: "login", sign_out: "logout"}


  namespace :admin do
    resources :admins,  except: [:show]
    resources :uploads, except: [:show, :edit, :update]
    resources :menus,   except: [:show] do
       post :page_sort, on: :collection
    end

    get "settings/homepage",       to: "settings#homepage",      as: :settings
    post "settings/homepage-save", to:  "settings#homepage_save", as: :homepage_save

    resources :pages do
       get   "sitemap",       on: :collection, as: :sitemap
       get   "clear_cache",   on: :collection, as: :clear_cache
    end
  end

  get ":permalink", to: "pages#show", as: :permalink
  root to: "pages#index"

   # Note: This route will make all actions in every controller accessible via GET requests.
   # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<title>Admin Panel | <%= title %></title>
	<meta name="robots" content="noindex, nofollow" />
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<%= stylesheet_link_tag "admin/all", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/themes/cupertino/jquery-ui.css" %>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag "modernizr-2.6.2.min.js" %>
</head>

<body>
	<div class="row-fluid">
			<header id="header">
				<hgroup>
					<h1 class="site_title"><%= link_to "", admin_pages_path, class: "admin_panel" %></h1>
					<div class="btn_view_site"><%= link_to "View Site", root_path %></div>
				</hgroup>
			</header> <!-- end of header bar -->

			<section id="secondary_bar">
				<div class="admin">
					<ul>
						<li style="float: left;"><i class="icon-user"></i>&nbsp;<%= current_admin.email %></li>
						<li style="float: right"><%= link_to(raw('&times;'), destroy_admin_session_path, method: :delete, class: "close logout_admin", title: "logout") %></li>
					</ul>
				</div>
				<%= render "admin/partials/breadcrumb" %>
			</section>
		</div>

		<div class="row-fluid">
			<div id="contentwrapper">
				<section id="main">
					<% if notice %><div class="alert alert-success"><button class="close" data-dismiss="alert" type="button">&times;</button><%= notice %></div><% end %>
					<% if alert %><div class="alert alert-error"><button class="close" data-dismiss="alert" type="button">&times;</button><%= alert %></div><% end %>
					<%= yield %>
				</section>
			</div>
			<%= render "admin/partials/sidebar" %>
	</div> <!-- end of #row-fluid -->

<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" %>
<script>window.jQuery || document.write('<script src="<%= asset_path("jquery.js") %>"><\/script>')</script>
<%= javascript_include_tag "admin/all" %>
<%= yield :custom_styling %>
<script>
	var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
	g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
<!--[if lt IE 7 ]>
	<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js" %>
	<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
<![endif]-->
</body>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<title></title>
	<meta name="description" content="">
	<meta name="author" content="John Deliyiannis, istoselidas@gmail.com">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<%= stylesheet_link_tag "application" %>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag "modernizr-2.0.6.min.js" %>
</head>


<body>
<div id="container">
	<header></header>
	<div id="main" role="main">
  		<%= yield %>
	</div>
	<footer></footer>
</div> <!--! end of #container -->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="<%= asset_path("jquery.js") %>"><\/script>')</script>
<%= javascript_include_tag "application" %>
<script>
	var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
	g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
<!--[if lt IE 7 ]>
	<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
	<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
<![endif]-->
</body>


</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
	<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
	<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
	<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
	<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
	<meta charset="utf-8" http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title><%= @page.title rescue "#{controller.action_name.titleize} #{controller.controller_name.titleize.singularize}" %></title>
	<meta name="description" content="<%= @page.meta_description rescue "#{controller.action_name.titleize} #{controller.controller_name.titleize.singularize}" %>">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<%= stylesheet_link_tag "pages/all" %>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag "modernizr-2.6.2.min.js" %>
</head>

	<body>
		<div id="container">
			<header id="header"><h1>Header</h1></header>
			<nav id="navbar">
				<%= render "pages/partials/menu" %>
			</nav>
			<div id="main" role="main">
				<%= yield %>
			</div>
			<footer id="footer"><h1>Footer</h1></footer>
		</div> <!-- end of #container -->

		<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" %>
    <script>window.jQuery || document.write('<script src="<%= asset_path("jquery.js") %>"><\/script>')</script>
		<%= javascript_include_tag "pages/all" %>
		<script>
			var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
			(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
			g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
			s.parentNode.insertBefore(g,s)}(document,'script'));
		</script>
		<!--[if lt IE 7 ]>
			<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js" %>
			<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
		<![endif]-->
		<%= yield :custom_styling if admin_signed_in? %>
	</body>


</html>

app/views/layouts/popup.html.erb
	<div id="container" class="popup">
		<section id="main" class="column" style="width: 375px">
		<% if notice %><h4 class="alert_success"><%= notice %></h4><% end %>
		<% if alert %><h4 class="alert_error"><%= alert %></h4><% end %>
			<%= yield %>
		</section>
	</div>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<title><%= yield(:title) || "#{controller.controller_name.titleize} #{controller.action_name.titleize}" %></title>
	<meta name="robots" content="noindex, nofollow" />
	<meta name="description" content="<%= yield(:title) || "#{controller.controller_name.titleize} #{controller.action_name.titleize}" %>">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<%= stylesheet_link_tag "sign_in" %>
	<%= csrf_meta_tags %>
	<%= javascript_include_tag "modernizr-2.6.2.min.js" %>
</head>


<body>
<div id="container">
  	<div id="main" role="main">
		<%= yield %>
	</div>
</div> <!--! end of #container -->

<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" %>
<script>window.jQuery || document.write('<script src="<%= asset_path("jquery.js") %>"><\/script>')</script>
<%= javascript_include_tag "sign_in" %>
<script>
	var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
	g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
<!--[if lt IE 7 ]>
	<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js" %>
  <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
<![endif]-->
</body>


</html>